# Generated by Django 3.2.8 on 2021-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_role_club_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='club_role',
            field=models.CharField(default='Applicant', max_length=10),
        ),
    ]
