# Generated by Django 3.2.8 on 2021-12-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_role_club_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='club_role',
            field=models.CharField(default='Applicant', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='chess_Level',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_statement',
            field=models.TextField(blank=True),
        ),
    ]
